version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-postgres
    environment:
      POSTGRES_DB: smarthome
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./my_app/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d smarthome"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    

  temperature-api:
    build: ./my_app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_NAME=smarthome
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - postgres
    restart: unless-stopped

  app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/smarthome
      - TEMPERATURE_API_URL=http://temperature-api:8081
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - smarthome-network

volumes:
  postgres_data:

networks:
  smarthome-network:
    driver: bridge